# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 12:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pin', '0007_auto_20160124_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instaaccount',
            name='lc',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 24, 15, 30, 37, 51728)),
        ),
        migrations.AlterField(
            model_name='log',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 24, 15, 30, 37, 55622)),
        ),
    ]
