# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mode',
            field=models.IntegerField(choices=[(1, b'normal'), (2, b'special')], default=1),
        ),
    ]
