# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 15:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import user_profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prof_id', models.IntegerField(default=0)),
                ('mode', models.IntegerField(blank=True, choices=[(1, b'Increment'), (2, b'Decrement')], default=1, null=True)),
                ('amount', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2016, 2, 9, 19, 5, 25, 947815))),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name=b'\xd9\x86\xd8\xa7\xd9\x85')),
                ('name1', models.CharField(max_length=250, verbose_name=b'd\xd9\x86\xd8\xa7\xd9\x85')),
                ('location', models.CharField(blank=True, max_length=250, verbose_name=b'\xd9\x85\xd9\x88\xd9\x82\xd8\xb9\xdb\x8c\xd8\xaa')),
                ('website', models.URLField(blank=True, verbose_name=b'\xd9\x88\xd8\xa8 \xd8\xb3\xd8\xa7\xdb\x8c\xd8\xaa')),
                ('bio', models.TextField(blank=True, verbose_name=b'\xd8\xaa\xd9\x88\xd8\xb6\xdb\x8c\xd8\xad\xd8\xa7\xd8\xaa')),
                ('cnt_post', models.IntegerField(default=0)),
                ('cnt_like', models.IntegerField(default=0)),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('count_flag', models.IntegerField(default=0)),
                ('trusted', models.IntegerField(default=0)),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to=user_profile.models.avatar_file_name)),
                ('jens', models.CharField(choices=[(b'M', b'\xd9\x85\xd8\xb0\xda\xa9\xd8\xb1'), (b'F', b'\xd9\x85\xd9\x88\xd9\x86\xd8\xab')], default=b'M', max_length=2)),
                ('fault', models.IntegerField(blank=True, default=0, null=True)),
                ('fault_minus', models.IntegerField(blank=True, default=0, null=True)),
                ('post_accept', models.BooleanField(default=False)),
                ('post_accept_admin', models.BooleanField(default=True)),
                ('email_active', models.BooleanField(default=False)),
                ('activation_key', models.CharField(blank=True, default=0, max_length=50)),
                ('cnt_following', models.IntegerField(blank=True, default=-1, null=True)),
                ('cnt_followers', models.IntegerField(blank=True, default=-1, null=True)),
                ('credit', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('banned', models.BooleanField(default=False)),
                ('version', models.IntegerField(default=0, null=True)),
                ('trusted_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trusted_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
