# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 11:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20160124_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 24, 15, 27, 44, 301000)),
        ),
    ]
