# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-24 12:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20160124_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditlog',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 1, 24, 15, 31, 14, 212771)),
        ),
    ]
